import type { L } from '../i18n';

export const s = {
  stage: { en: 'Stage', fr: 'Niveau' },
  loading: { en: 'Loading…', fr: 'Chargement…' },
  menu: { en: 'Menu', fr: 'Menu' },
  close: { en: 'Close', fr: 'Fermer' },
  start: { en: 'Start', fr: 'Commencer' },
  replay: { en: 'Play again', fr: 'Rejouer' },
  skip: { en: 'Skip stage', fr: 'Passer le niveau' },
  skipForNow: { en: 'Skip for now', fr: 'Passer pour l’instant' },
  reset: { en: 'Reset', fr: 'Recommencer' },
  exit: { en: 'Exit', fr: 'Quitter' },
  back: { en: 'Back', fr: 'Retour' },
  hideRules: { en: 'Hide rules', fr: 'Masquer les règles' },
  showRules: { en: 'Rules', fr: 'Règles' },
  continue: { en: 'Continue', fr: 'Continuer' },
  enter: { en: 'Enter', fr: 'Entrer' },
  jump: { en: 'Jump', fr: 'Sauter' },
  left: { en: 'Move left', fr: 'Aller à gauche' },
  right: { en: 'Move right', fr: 'Aller à droite' },
  keysHint: {
    en: '← → move · Space jump · E enter',
    fr: '← → se déplacer · Espace sauter · E entrer',
  },
  pickOutfit: { en: 'Choose your outfit', fr: 'Choisissez votre tenue' },
  outfitIntro: {
    en: 'It’s 2010 and you’re starting at École Polytechnique. You can change outfits any time at the school’s door.',
    fr: 'Nous sommes en 2010, vous entrez à l’École polytechnique. Vous pourrez changer de tenue à tout moment devant l’école.',
  },
  outfitPolytechnique: { en: 'Grand uniform & bicorne', fr: 'Grand uniforme & bicorne' },
  outfitPolytechniqueSub: { en: 'École Polytechnique', fr: 'École polytechnique' },
  outfitSWE: { en: 'Jeans & t-shirt', fr: 'Jean & t-shirt' },
  outfitSWESub: { en: 'Software eng.', fr: 'Développeur' },
  collectHint: {
    en: 'Jump onto the platforms to collect both diplomas.',
    fr: 'Sautez sur les plateformes pour récupérer les deux diplômes.',
  },
  collected: { en: 'Collected', fr: 'Obtenu' },
  stageComplete: { en: 'Stage complete!', fr: 'Niveau terminé !' },
  unlocked: { en: 'Unlocked', fr: 'Débloqué' },
  gateOpen: { en: 'The next gate is open →', fr: 'La porte suivante est ouverte →' },
  comingSoon: {
    en: 'This mini-game is still being built. You can skip ahead for now.',
    fr: 'Ce mini-jeu est encore en construction. Vous pouvez passer pour l’instant.',
  },
  stuck: {
    en: 'Out of moves: stuck in a local optimum! Reset and try again.',
    fr: 'Plus de coups : bloqué dans un optimum local ! Recommencez.',
  },
  done: { en: 'Done', fr: 'Terminé' },
  locked: { en: 'Locked', fr: 'Verrouillé' },
  travel: { en: 'Go', fr: 'Aller' },
  resetProgress: { en: 'Reset progress', fr: 'Réinitialiser la progression' },
  resetConfirm: { en: 'Erase your progress and start over?', fr: 'Effacer votre progression et recommencer ?' },
  resume: { en: 'Resume', fr: 'CV' },
  finishTitle: { en: 'Thanks for playing!', fr: 'Merci d’avoir joué !' },
  finishBody: {
    en: 'That’s the story so far. Want the short version, or to get in touch?',
    fr: 'Voilà l’histoire jusqu’ici. Envie de la version courte, ou de me contacter ?',
  },
  finishEarly: {
    en: 'You reached the end of the road! Some stages were skipped: come back to finish them.',
    fr: 'Vous êtes arrivé au bout du chemin ! Certains niveaux ont été passés : revenez les terminer.',
  },
  inventory: { en: 'Inventory', fr: 'Inventaire' },
  finish: { en: 'Finish', fr: 'Arrivée' },
} satisfies Record<string, L>;
